---
title: "Visualization: Mar 2024"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

## Including libraries

```{r, warning=FALSE}

library(dplyr)
library(xgboost)
library(caret)
require(tidyr)
library(ggplot2)
library(reshape)
library(stargazer)
library(cowplot)
library(magick)
# library(MASS)
library(ggalt) # for geom_encircle
library(purrr)
library(xtable)
library(ggrepel)
library(grid)
library(jpeg)
library(data.table)
library(geometry)
library(purrr)
library(sp)
library(sf)
library(Rtsne)
# library(Cairo)
rm(list=ls())
set.seed(123)

```

## Reading Structured Data

```{r, warning=FALSE}

uk_product_data <- read.csv('exp_uk_product_data.csv', stringsAsFactors=FALSE)

uk_product_data$Viz1 <- NULL
uk_product_data$Viz2 <- NULL
uk_product_data$Viz3 <- NULL
uk_product_data$Viz4 <- NULL
uk_product_data$Viz5 <- NULL

uk_product_data$supply_instruments0 <- NULL
uk_product_data$supply_instruments1 <- NULL
uk_product_data$supply_instruments2 <- NULL
uk_product_data$supply_instruments3 <- NULL
uk_product_data$supply_instruments4 <- NULL
uk_product_data$supply_instruments5 <- NULL
uk_product_data$supply_instruments6 <- NULL
uk_product_data$supply_instruments7 <- NULL
uk_product_data$supply_instruments8 <- NULL
uk_product_data$supply_instruments9 <- NULL

uk_product_data$demand_instruments0 <- NULL
uk_product_data$demand_instruments1 <- NULL
uk_product_data$demand_instruments2 <- NULL
uk_product_data$demand_instruments3 <- NULL
uk_product_data$demand_instruments4 <- NULL
uk_product_data$demand_instruments5 <- NULL
uk_product_data$demand_instruments6 <- NULL
uk_product_data$demand_instruments7 <- NULL

uk_product_data$Domestic <- ifelse(uk_product_data$region=="United Kingdom",1,0)
uk_product_data$France <- ifelse(uk_product_data$region=="France",1,0)
uk_product_data$Germany <- ifelse(uk_product_data$region=="Germany",1,0)
uk_product_data$Japan <- ifelse(uk_product_data$region=="Japan",1,0)
uk_product_data$Korea <- ifelse(uk_product_data$region=="South Korea",1,0)
uk_product_data$USA <- ifelse(uk_product_data$region=="United States",1,0)

summary_stats <- uk_product_data %>% group_by(market_ids) %>% summarise(models=n(),Quantity=mean(quantity),price=sum(prices*shares)/sum(shares),Domestic=sum(Domestic*shares)/sum(shares),France=sum(France*shares)/sum(shares),Germany=sum(Germany*shares)/sum(shares),Japan=sum(Japan*shares)/sum(shares),Korea=sum(Korea*shares)/sum(shares),USA=sum(USA*shares)/sum(shares),hpwt=sum(hpwt*shares)/sum(shares),space=sum(space*shares)/sum(shares),mpg=sum(mpg*shares)/sum(shares),mpd=sum(mpd*shares)/sum(shares))

temp <- uk_product_data %>% summarise(models=n(),Quantity=mean(quantity),price=sum(prices*quantity)/sum(quantity),Domestic=sum(Domestic*quantity)/sum(quantity),France=sum(France*quantity)/sum(quantity),Germany=sum(Germany*quantity)/sum(quantity),Japan=sum(Japan*quantity)/sum(quantity),Korea=sum(Korea*quantity)/sum(quantity),USA=sum(USA*quantity)/sum(quantity),hpwt=sum(hpwt*quantity)/sum(quantity),space=sum(space*quantity)/sum(quantity),mpg=sum(mpg*quantity)/sum(quantity),mpd=sum(mpd*quantity)/sum(quantity))

temp <- cbind("All",temp)
names(temp)[1] <- "market_ids"

summary_stats <- rbind(summary_stats,temp)

rm(temp)

uk_product_data$Domestic <- NULL
uk_product_data$France <- NULL
uk_product_data$Germany <- NULL
uk_product_data$Japan <- NULL
uk_product_data$Korea <- NULL
uk_product_data$USA <- NULL

summary_stats$Quantity <- summary_stats$Quantity/1000
summary_stats[,3:14] <- round(summary_stats[,3:14],3)
print(summary_stats %>% as.data.frame())
# Table 6: Descriptive Statistics of Structured Data
subset_stats <- summary_stats[, c(1:4, 11:14)] %>% as.data.frame()
names(subset_stats) <- c("Market","No. of Observations","Quantity","Price","HP/Wt","Space","MPG","MP\\textsterling")
print(subset_stats)
xtable(subset_stats)


```

## Reading Visual Data

```{r, warning=FALSE}
filename_train <- read.csv('xife_s5b50m40_filename_train.csv', stringsAsFactors=FALSE, header=FALSE)
filename_valid <- read.csv('xife_s5b50m40_filename_validation.csv', stringsAsFactors=FALSE, header=FALSE)
mean_params_train <- read.csv('xife_s5b50m40_mean_params_train.csv', stringsAsFactors=FALSE, header=FALSE)
mean_params_valid <- read.csv('xife_s5b50m40_mean_params_validation.csv', stringsAsFactors=FALSE, header=FALSE)

mean_params <- rbind(mean_params_train,mean_params_valid)
filename <- rbind(filename_train,filename_valid)
visual_att <- cbind(filename,mean_params)
rm(mean_params_train,mean_params_valid,filename_train,filename_valid,filename,mean_params)
colnames(visual_att)[1] <- "Image_name"

select_image_table <- read.csv('exp_selected_python_image_table.csv',stringsAsFactors = FALSE)

select_visual_att <- merge(select_image_table,visual_att)

select_visual_att <- select_visual_att %>% dplyr::select(Image_name,make,model,market_ids,gen_ids,car_ids,bodyshape=V13,grille_height=V7,boxiness=V15,grille_width=V17)

```

## Merging Structured & Visual Data

```{r, warning=FALSE}

df_data <- merge(uk_product_data,select_visual_att,all.x = TRUE)
temp <- df_data %>% filter(is.na(Image_name))

df_data$old_segment_desc <- df_data$Segment_Desc
df_data$segment_name <- ifelse(df_data$Segment_Desc=="A-Segment (Minicars)","A",ifelse(df_data$Segment_Desc=="B-segment (subcompact)","B",ifelse(df_data$Segment_Desc=="C-segment (compact)","C",ifelse(df_data$Segment_Desc=="D-segment (mid-size)","D",ifelse(df_data$Segment_Desc=="E-segment (mid-size luxury sedan)","E",ifelse(df_data$Segment_Desc=="J-segment (SUV)","J",ifelse(df_data$Segment_Desc=="M-segment (MPV)","M","X")))))))
df_data$Segment_Desc <- NULL

df_make_selection1 <- df_data %>% group_by(market_ids,segment_name) %>% summarise(markets=n(),image_avail=sum(!is.na(gen_ids)),total_quantity=sum(quantity))
df_make_selection1$pc_image_avail <- df_make_selection1$image_avail/df_make_selection1$markets

df_make_selection2 <- df_data %>% group_by(market_ids,segment_name) %>% filter(!is.na(gen_ids)) %>%  summarise(available_quantity=sum(quantity))

df_make_selection <- merge(df_make_selection1,df_make_selection2,all.x = TRUE)
df_make_selection$pc_image_qty <- df_make_selection$available_quantity/df_make_selection$total_quantity
df_make_selection$markets <- NULL
df_make_selection$image_avail <- NULL
df_make_selection$total_quantity <- NULL
df_make_selection$available_quantity <- NULL

rm(df_make_selection1,df_make_selection2)

df_data <- df_data %>% filter(!is.na(gen_ids)) %>% dplyr::select(clustering_ids,make,model,market_ids,segment_name,car_ids,firm_ids,quantity,shares,prices,mpg,hpwt,space,Seats,Doors,mpd,boxiness,bodyshape,grille_height,grille_width,Image_name)

```

## Preparing Data for Market Structure TSNE

```{r}

segment_value <- sort(unique(df_data$segment_name))

names(df_data)[names(df_data) == "prices"] <- "X1 - Price"
names(df_data)[names(df_data) == "mpg"] <- "X2 - MPG"
names(df_data)[names(df_data) == "hpwt"] <- "X3 - HPWT"
names(df_data)[names(df_data) == "space"] <- "X4 - Space"
names(df_data)[names(df_data) == "boxiness"] <- "V1 - Boxiness"
names(df_data)[names(df_data) == "bodyshape"] <- "V2 - Body Shape"
names(df_data)[names(df_data) == "grille_height"] <- "V3 - Grille Height"
names(df_data)[names(df_data) == "grille_width"] <- "V4 - Grille Width"

df_data$Image_name <- paste0("../market_structure/original/",df_data$Image_name)

```

## Correlation

```{r}

cor_matrix <- df_data %>% dplyr::select(`X1 - Price`, `X2 - MPG`, `X3 - HPWT`, `X4 - Space`, `V1 - Boxiness`, `V2 - Body Shape`, `V3 - Grille Height`, `V4 - Grille Width`) %>% cor()
latex_table <- xtable(cor_matrix, caption = "Correlation Matrix")
# Table 8: Correlation Matrix
print(latex_table)

```

## Selecting Top N Makes

```{r}

top_makes_for_latex <- df_data %>% filter(segment_name == "B" | segment_name == "D" | segment_name == "J") %>% group_by(make) %>% summarise(total_shares = sum(shares)) %>% slice_max(order_by = total_shares, n = 5) %>% pull(make)
for_latex <- df_data %>% filter(make %in% top_makes_for_latex)

# Table 9: Product Characteristics
for(market in 2008:2017){
  df_temp <- for_latex %>% filter(market_ids==market) %>% filter(segment_name == "B" | segment_name == "D" | segment_name == "J")
  subset_df <- df_temp[, c("segment_name", "make", "model", "X1 - Price", "X2 - MPG", "X3 - HPWT", "X4 - Space", "V1 - Boxiness", "V2 - Body Shape", "V3 - Grille Height", "V4 - Grille Width")]
  subset_df <- subset_df[order(subset_df$segment_name, subset_df$make, subset_df$model),]
  latex_table <- xtable(subset_df, caption = "Table caption", label = "tab:mytable")
  colnames(latex_table) <- c("Segment", "Make", "Model", "X1 - Price", "X2 - MPG", "X3 - HPWT", "X4 - Space", "V1 - Boxiness", "V2 - Body Shape", "V3 - Grille Height", "V4 - Grille Width")
  print(latex_table, include.rownames = FALSE, include.colnames = TRUE, hline.after = c(-1, 0, nrow(subset_df)))
}


```

## TSNE

```{r}

# Step 1: Subset the data
str_subset_data <- df_data[, c("clustering_ids", "make", "model", "market_ids", "segment_name", "shares", "Image_name", "X1 - Price", "X3 - HPWT", "X2 - MPG", "X4 - Space")]
str_subset_data$`X1 - Price` <- (log10(str_subset_data$`X1 - Price`)-mean(log10(str_subset_data$`X1 - Price`)))/sd(log10(str_subset_data$`X1 - Price`))
str_subset_data$`X3 - HPWT` <- (log10(str_subset_data$`X3 - HPWT`)-mean(log10(str_subset_data$`X3 - HPWT`)))/sd(log10(str_subset_data$`X3 - HPWT`))
str_subset_data$`X2 - MPG` <- (str_subset_data$`X2 - MPG` - mean(str_subset_data$`X2 - MPG`))/sd(str_subset_data$`X2 - MPG`)
str_subset_data$`X4 - Space` <- (str_subset_data$`X4 - Space` - mean(str_subset_data$`X4 - Space`))/sd(str_subset_data$`X4 - Space`)

# Step 2: Perform TSNE on the subset of data and extract s_x and s_y
str_tsne_data <- Rtsne(str_subset_data[, 8:11], check_duplicates = FALSE)
str_tsne_data <- str_tsne_data$Y

# Create a data frame with the TSNE coordinates and other variables of interest
str_tsne_data_df <- data.frame(s_x = str_tsne_data[, 1], s_y = str_tsne_data[, 2], clustering_ids = str_subset_data$clustering_ids, make = str_subset_data$make, model = str_subset_data$model, market_ids = str_subset_data$market_ids, segment_name = str_subset_data$segment_name, shares = str_subset_data$shares, image_file = str_subset_data$Image_name)

# Step 1: Subset the data
viz_subset_data <- df_data[, c("clustering_ids", "make", "model", "market_ids", "segment_name", "shares","Image_name", "V1 - Boxiness", "V2 - Body Shape", "V3 - Grille Height", "V4 - Grille Width")]
df_summary <- viz_subset_data
df_summary$Image_name <- NULL
df_summary$shares <- NULL
df_summary$market_ids <- NULL
df_summary$clustering_ids <- NULL
df_summary <- unique(df_summary)
viz_subset_data$`V1 - Boxiness` <- (viz_subset_data$`V1 - Boxiness` - mean(df_summary$`V1 - Boxiness`))/sd(df_summary$`V1 - Boxiness`)
viz_subset_data$`V2 - Body Shape` <- (viz_subset_data$`V2 - Body Shape` - mean(df_summary$`V2 - Body Shape`))/sd(df_summary$`V2 - Body Shape`)
viz_subset_data$`V3 - Grille Height` <- (viz_subset_data$`V3 - Grille Height` - mean(df_summary$`V3 - Grille Height`))/sd(df_summary$`V3 - Grille Height`)
viz_subset_data$`V4 - Grille Width` <- (viz_subset_data$`V4 - Grille Width` - mean(df_summary$`V4 - Grille Width`))/sd(df_summary$`V4 - Grille Width`)

# Step 2: Perform TSNE on the subset of data and extract s_x and s_y
viz_tsne_data <- Rtsne(viz_subset_data[, 8:11], check_duplicates = FALSE)
viz_tsne_data <- viz_tsne_data$Y

# Create a data frame with the TSNE coordinates and other variables of interest
viz_tsne_data_df <- data.frame(v_x = viz_tsne_data[, 1], v_y = viz_tsne_data[, 2], clustering_ids = str_subset_data$clustering_ids, make = str_subset_data$make, model = str_subset_data$model, market_ids = str_subset_data$market_ids, segment_name = str_subset_data$segment_name, shares = str_subset_data$shares, image_file = str_subset_data$Image_name)

# Step 1: Subset the data
mix_subset_data <- df_data[, c("clustering_ids", "make", "model", "market_ids", "segment_name", "shares", "Image_name", "X1 - Price", "X3 - HPWT", "X2 - MPG", "X4 - Space", "V1 - Boxiness", "V2 - Body Shape", "V3 - Grille Height", "V4 - Grille Width")]

mix_subset_data$`X1 - Price` <- (log10(mix_subset_data$`X1 - Price`)-mean(log10(mix_subset_data$`X1 - Price`)))/sd(mix_subset_data$`X1 - Price`)
mix_subset_data$`X3 - HPWT` <- (log10(mix_subset_data$`X3 - HPWT`)-mean(log10(mix_subset_data$`X3 - HPWT`)))/sd(mix_subset_data$`X3 - HPWT`)
mix_subset_data$`X2 - MPG` <- (mix_subset_data$`X2 - MPG` - mean(mix_subset_data$`X2 - MPG`))/sd(mix_subset_data$`X2 - MPG`)
mix_subset_data$`X4 - Space` <- (mix_subset_data$`X4 - Space` - mean(mix_subset_data$`X4 - Space`))/sd(mix_subset_data$`X4 - Space`)
mix_subset_data$`V1 - Boxiness` <- (mix_subset_data$`V1 - Boxiness` - mean(df_summary$`V1 - Boxiness`))/sd(df_summary$`V1 - Boxiness`)
mix_subset_data$`V2 - Body Shape` <- (mix_subset_data$`V2 - Body Shape` - mean(df_summary$`V2 - Body Shape`))/sd(df_summary$`V2 - Body Shape`)
mix_subset_data$`V3 - Grille Height` <- (mix_subset_data$`V3 - Grille Height` - mean(df_summary$`V3 - Grille Height`))/sd(df_summary$`V3 - Grille Height`)
mix_subset_data$`V4 - Grille Width` <- (mix_subset_data$`V4 - Grille Width` - mean(df_summary$`V4 - Grille Width`))/sd(df_summary$`V4 - Grille Width`)

# Step 2: Perform TSNE on the subset of data and extract s_x and s_y
mix_tsne_data <- Rtsne(mix_subset_data[, 8:15], check_duplicates = FALSE)
mix_tsne_data <- mix_tsne_data$Y

# Create a data frame with the TSNE coordinates and other variables of interest
mix_tsne_data_df <- data.frame(m_x = mix_tsne_data[, 1], m_y = mix_tsne_data[, 2], clustering_ids = str_subset_data$clustering_ids, make = str_subset_data$make, model = str_subset_data$model, market_ids = str_subset_data$market_ids, segment_name = str_subset_data$segment_name, shares = str_subset_data$shares, image_file = str_subset_data$Image_name)

```

## Survey Choices

```{r}

df <- merge(str_tsne_data_df %>% select(s_x,s_y,make,model,market_ids,segment_name),viz_tsne_data_df %>% select(v_x,v_y,make,model,market_ids,segment_name),by=c("make","model","market_ids","segment_name"))


pair_make_models <- function(df,year) {
  
df1 <- df %>% filter(market_ids==year)
df_make_model <- df1 %>% mutate(make_model = paste(make, model, sep = " ")) %>% select(make_model) %>% distinct()
coords_s <- df1[, c("s_x", "s_y")]
distance_matrix_s <- as.matrix(dist(coords_s))
coords_v <- df1[, c("v_x", "v_y")]
distance_matrix_v <- as.matrix(dist(coords_v))

distance_matrix_s_percentile <- apply(distance_matrix_s, c(1, 2), function(x) ecdf(distance_matrix_s)(x) * 100)

distance_matrix_v_percentile <- apply(distance_matrix_v, c(1, 2), function(x) ecdf(distance_matrix_v)(x) * 100)

close_s_far_v <- (distance_matrix_s_percentile < 10) & (distance_matrix_v_percentile > 90)

close_v_far_s <- (distance_matrix_v_percentile < 10) & (distance_matrix_s_percentile > 90)

indices_s_v <- which(close_s_far_v, arr.ind = TRUE)
pair_close_s_far_v <- data.frame(
  make_model1 = df_make_model$make_model[indices_s_v[, 1]],
  make_model2 = df_make_model$make_model[indices_s_v[, 2]]
)

indices_v_s <- which(close_v_far_s, arr.ind = TRUE)
pair_close_v_far_s <- data.frame(
  make_model1 = df_make_model$make_model[indices_v_s[, 1]],
  make_model2 = df_make_model$make_model[indices_v_s[, 2]]
)

return(list(pair_close_s_far_v, pair_close_v_far_s))

}

pairs <- pair_make_models(df,2013)
close_s_far_v <- pairs[[1]]
close_v_far_s <- pairs[[2]]

df_data_make_model <- df_data %>% filter(market_ids==2013) %>%  mutate(make_model = paste(make, model, sep = " ")) %>% select(make_model, segment_name, quantity, price=`X1 - Price`,mpg=`X2 - MPG`,hpwt=`X3 - HPWT`,space=`X4 - Space`, image_name=`Image_name`)

close_s_far_v_augmented1 <- close_s_far_v %>% left_join(df_data_make_model, by = c("make_model1" = "make_model")) %>% rename_with(~paste0(., "1"), -c(make_model1, make_model2))

close_s_far_v_augmented2 <- close_s_far_v %>% left_join(df_data_make_model, by = c("make_model2" = "make_model")) %>% rename_with(~paste0(., "2"), -c(make_model1, make_model2))

close_s_far_v_augmented <- merge(close_s_far_v_augmented1,close_s_far_v_augmented2)
rm(close_s_far_v_augmented1,close_s_far_v_augmented2)

close_s_far_v_augmented <- close_s_far_v_augmented %>% filter(quantity1>999 & quantity2>999)

close_v_far_s_augmented1 <- close_v_far_s %>% left_join(df_data_make_model, by = c("make_model1" = "make_model")) %>% rename_with(~paste0(., "1"), -c(make_model1, make_model2))

close_v_far_s_augmented2 <- close_v_far_s %>% left_join(df_data_make_model, by = c("make_model2" = "make_model")) %>% rename_with(~paste0(., "2"), -c(make_model1, make_model2))

close_v_far_s_augmented <- merge(close_v_far_s_augmented1,close_v_far_s_augmented2)
rm(close_v_far_s_augmented1,close_v_far_s_augmented2)

close_v_far_s_augmented <- close_v_far_s_augmented %>% filter(quantity1>999 & quantity2>999)

rm(close_s_far_v,close_v_far_s)

close_v_far_s_augmented <- close_v_far_s_augmented %>% filter(segment_name1!="J" & segment_name2!="J" & segment_name1!="M" & segment_name2!="M")

close_s_far_v_augmented <- close_s_far_v_augmented %>% filter(segment_name1!="J" & segment_name2!="J" & segment_name1!="M" & segment_name2!="M")

close_v_far_s_augmented <- close_v_far_s_augmented %>% select(make_model1,make_model2,segment_name1,segment_name2,price1,mpg1,hpwt1,space1,price2,mpg2,hpwt2,space2,image_name1,image_name2,quantity1,quantity2)
```

